resolver: lts-16.16

packages:
  - cas/hashable
  - cas/s3
  - cas/store
  - external-executor
  - docker-client
  - funflow

# Reminder: These are extra packages which don't exist in the
# stack snapshot we are using.
extra-deps:
  - aws-0.22
  - direct-sqlite-2.3.26
  - github: jgm/cheapskate
    commit: 7287cfd8f08c4c49e4ad4f300b5b19c4377cb094
  - github: GuillaumeDesforges/inliterate
    commit: 1a7e082d1106e11466e16fbb4707837c7b6e9761
  - github: tweag/kernmantle
    commit: 79e5cf5ecfe73f41206aa78930256a2f171bc9b8
    subdirs:
      - kernmantle
      - batteries
      - caching
  # We use iHaskell for the tutorials
  - github: gibiansky/IHaskell
    commit: ef698157f44960566687a308e3455b5ba031eb43
    subdirs:
      - .
      - ipython-kernel
      - ghc-parser
      - ihaskell-display/ihaskell-aeson
      - ihaskell-display/ihaskell-blaze
      - ihaskell-display/ihaskell-charts
      - ihaskell-display/ihaskell-diagrams
      - ihaskell-display/ihaskell-gnuplot
      - ihaskell-display/ihaskell-hatex
      - ihaskell-display/ihaskell-juicypixels
      - ihaskell-display/ihaskell-magic
      - ihaskell-display/ihaskell-widgets
  # We also provide hvega for plotting
  - github: DougBurke/hvega
    commit: 58a6861a3ebecdfe2ade149c1bff3064341fee33
    subdirs:
      - ihaskell-hvega
  - sqlite-simple-0.4.18.0
  - store-0.7.4
  - store-core-0.4.4.2
  - th-utilities-0.2.4.0
  - vinyl-0.12.2

nix:
  enable: true
  shell-file: shell-stack.nix
