resolver: lts-15.14

packages:
  - cas/hashable
  - cas/s3
  - cas/store
  - external-executor
  - funflow
  - funflow-aws
  - funflow-checkpoints
  - funflow-cwl
  - funflow-examples
  - funflow-jobs
  - funflow2

extra-deps:
  - aws-0.22
  - sqlite-simple-0.4.18.0
  - store-0.7.4
  - direct-sqlite-2.3.26
  - store-core-0.4.4.2
  - th-utilities-0.2.4.0
  - vinyl-0.12.2
  - github: tweag/kernmantle
    commit: 79e5cf5ecfe73f41206aa78930256a2f171bc9b8
    subdirs:
      - kernmantle
      - batteries
      - caching

nix:
  packages:
    - zlib
    - docker
    - nix
