name: funflow2-tutorial
version: 0.1.0
synopsis: A tutorial on how to use funflow2
description: See README at <https://github.com/tweag/funflow2>
maintainer: Guillaume Desforges <guillaume.desforges@tweag.io>
github: tweag/funflow2
category: Development

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - funflow2
  - inliterate

library:
  source-dirs: lib

executables:
  quick-reference:
    main: src/QuickReference.hs
    source-dirs: .
    dependencies:
      - base >=4.6 && <5
      - funflow2-tutorial
    build-tools:
      - inliterate:inlitpp
  tutorial1:
    main: src/Tutorial1.hs
    source-dirs: .
    dependencies:
      - base >=4.6 && <5
      - funflow2-tutorial
    build-tools:
      - inliterate:inlitpp
