name: funflow2
version: 0.1.0
synopsis: Make composable workflows
description: See README at <https://github.com/tweag/funflow/funflow2>
maintainer: Guillaume Desforges <guillaume.desforges@tweag.io>
github: tweag/funflow/funflow2
category: Development

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - cas-store
  - cas-hashable
  - data-default
  - external-executor
  - hashable
  - katip
  - kernmantle
  - kernmantle-batteries
  - kernmantle-caching
  - modern-uri
  - path
  - process
  - store
  - text

library:
  source-dirs: src

tests:
  test-funflow:
    main: TestFunflow.hs
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - base >=4.6 && <5
      - funflow2
# Test-suite unit-tests
#   type:               exitcode-stdio-1.0
#   default-language:   Haskell2010
#   hs-source-dirs:     test
#   main-is:            Test.hs
#   other-modules:      Funflow.SQLiteCoordinator
#                       Funflow.TestFlows
#                       Control.Arrow.Async.Tests
#   ghc-options:        -Wall -threaded
#   build-depends:      base
#                     , async
#                     , cas-store
#                     , data-default >= 0.7
#                     , directory
#                     , filepath
#                     , funflow
#                     , path
#                     , path-io
#                     , process
#                     , random
#                     , safe-exceptions
#                     , tasty
#                     , tasty-hunit
#                     , temporary
#                     , unix
