name: external-executor
version: 0.1.0
synopsis: Run external tasks and coordinate them
description: See README at <https://github.com/tweag/funflow/external-executor>
maintainer: Guillaume Desforges <guillaume.desforges@tweag.io>
github: tweag/funflow/external-executor
category: Development

ghc-options: -Wall

dependencies:
  - aeson
  - async
  - base >= 4.9
  - bytestring
  - cas-store
  - cas-hashable
  - clock
  - containers
  - hedis
  - hostname
  - katip
  - lens
  - mtl
  - path
  - path-io
  - process
  - safe-exceptions
  - sqlite-simple
  - stm
  - store
  - text
  - transformers
  - unix

library:
  source-dirs: src
