name: funflow2 CI (Linux, Nix)

on: [push]

jobs:
  build:
    name: funflow2 [build >> tests >> doc]
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v9
        # with:
        #   skip_adding_nixpkgs_channel: true
      - uses: cachix/cachix-action@v6
        with:
          name: tweag-funflow2
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      # Builds
      - name: Build funflow library
        run: nix-build -A funflow
      - name: Build funflow tests 
        run: |
          echo Build tests
          TESTS_PATH=$(nix-build -A funflow-tests)
          echo Running tests
          $TESTS_PATH/bin/test-funflow
      # Build documentation
      - name: Build docs and tutorials
        run: |
          nix-build -A combined-docs -o funflow-docs
          # Need to materialize documentation symlinks here
          # since the deploy stage below doesn't deep copy
          cp -rL ./funflow-docs ./funflow-docs-materialized
      # Deploy documentation to a github page
      - name: Deploy docs
        # Push to GitHub Pages only on master
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./funflow-docs-materialized/share
